### ISSUE TITLE
Releases after 2.1.8 are not compatible with older versions

### ISSUE THREAD

**Issue by sergiu-paraschiv** [bestander/npm-git-lock#15]
The hash generated by 2.1.8 is different than the one generated by 3.x.x for the same `package.json`.
This being a `npm install -g` module one can _easily_ forget to update it locally.
I know I can and _should_ update my "setting up a dev environment" document to say `npm install -g npm-git-lock@x.y.z` but please add a big Changelog section somewhere in README.md making this clear :)

Great tool otherwise.

**Comment by bestander** [comment]
Oh yeah, sorry for inconvenience, I did think about breaking change, that is why I bumped major version.
But screwed up by not doing aChangelog.

Hey, if you submit a PR, I would merge it :)
Does not need to be full, just a note that you described would be a good first step.

**Comment by sergiu-paraschiv** [comment]
Done https://github.com/bestander/npm-git-lock/pull/16

**Comment by bestander** [comment]
done and done
thanks
