### ISSUE TITLE
Support for typings folder

### ISSUE THREAD

**Issue by capi** [bestander/npm-git-lock#17]
Similar to the `node_modules`, it would be very interesting to also lock the `typings` folder, since it would also help in reducing external connection requirements.

**Comment by bestander** [comment]
I suppose this can be generalized quite easily.
"node_modules" is repeated 18 times in the code.
Just extract it into the variable and allow overriding.
PR is welcome.

**Comment by bestander** [comment]
Feel free to open PR for that, I'll close it because it is not an issue
