### ISSUE TITLE
loglevel parameter is incorrect

### ISSUE THREAD

**Issue by jderose9** [bestander/npm-git-lock#18]
The loglevel parameter passed to npm in npmRunCommands() in checkout-node-module.js should be "--loglevel" and not "--log-level" with a dash.

This is causing an issue for me because TFS Build treats anything written to STDERR as a build failure, which is where npm writes warnings. When I make this change locally, it properly silences npm warnings when the -v flag is absent.

BTW.. Thanks for this nice tool and comprehensive blog post!

**Comment by bestander** [comment]
@jderose9 thanks for the kind words.
Thanks for reporting the bug, would you care to create a PR?

**Comment by jderose9** [comment]
done! thanks.
