### ISSUE TITLE
`preinstall` and `postinstall`

### ISSUE THREAD

**Issue by skevy** [bestander/npm-git-lock#20]
I noticed that because you have to use `--ignore-scripts` when doing `--cross-platform`, that pre and post install scripts in my project are no longer run (which makes sense haha).

Thoughts on manually calling `preinstall` and `postinstall` if `--cross-platform` is set? Happy to submit a PR.

**Comment by bestander** [comment]
Go for it.
As long as current functionality does not break, I am fine with it.
You don't use it standalone but part of the project?
