### ISSUE TITLE
Production only option?

### ISSUE THREAD

**Issue by faceleg** [bestander/npm-git-lock#22]
As a user of this module I'd love to be able to supply a `--production` flag to have only production modules installed / tracked

**Comment by bestander** [comment]
Sounds reasonable.
Would you care to do a PR?

**Comment by faceleg** [comment]
I'd like to, but probably won't be able to in the near future.

**Comment by bestander** [comment]
Ok, I'll leave this open, up for grabs.
If more people will +1 here I'll implement it myself
