### ISSUE TITLE
Should --cross-platform run 'npm install'?

### ISSUE THREAD

**Issue by fdattein** [bestander/npm-git-lock#28]
Hi there,

as title says, should --cross-platform run 'npm install'? I would guess it shouldn't, because some platform specific dependencies, such as dbus, are likely to fail as they aren't multi-platform.

My project is meant to run on a RPI(arm), my dev machine is MacOS and CI is Ubuntu Linux (x64). 
When I run the command below on MacOS, it fails because some of my dependencies are RPI specific.

```
npm-git-lock --cross-platform --incremental-install --production --repo [my repo url] -v
```

Therefore, node_modules never gets push to its repor, despite being installable in the end users machine(RPI).

Thoughts?

**Comment by bestander** [comment]
Npm can be quite tricky, for example there are `optionalDependencies` that just won't be installed on platform that does not support the this dependency.

In your case I would not rely on `--cross-platform` option and use 3 git repositories for all 3 environments: Mac, linux x-86 and linux arm.
Feel free to reopen issue
