### ISSUE TITLE
Error with --cross-platform option and scoped packages on npm v5.x

### ISSUE THREAD

**Issue by splotzky** [bestander/npm-git-lock#38]
With the option `--cross-platform` and npm v5.x while having a [scoped package][1] in the `package.json`, npm-git-lock tries to rebuild the scope folder instead of the packages contained in the scope.

For npm v3.x this was not a problem, as the rebuild command for the scope folder did nothing.
However, for npm v5.x, it throws the following exception (here with `@angular/cli`):

```
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "@angular": Tags may not have any characters that encodeURIComponent encodes.
npm command 'rebuild' failed:
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "@angular": Tags may not have any characters that encodeURIComponent encodes.
```

[1]: https://docs.npmjs.com/misc/scope

**Comment by bestander** [comment]
Weird, looks like some problem with npm handling the package name, similar to this issue https://github.com/npm/npm/issues/16981

Rebuild  command is here https://github.com/bestander/npm-git-lock/blob/master/src/checkout-node-modules.es6#L243 but I don't have enough context if we can do a workaround.
A PR with a fix is welcome

**Comment by splotzky** [comment]
Perfect!
