### ISSUE TITLE
Support yarn, pnpm and so on

### ISSUE THREAD

**Issue by DanielRuf** [bestander/npm-git-lock#40]
Is it possible to use Yarn and pnpm with this?
Because it seems that there is currently an npm package to run npm scripts but we would like to use Yarn or pnpm instead.

Would be good to have some flag to change the used package manager.

**Comment by DanielRuf** [comment]
Also Yarn PnP needs to be supported.

**Comment by bestander** [comment]
Hey @DanielRuf.
I npm-git-lock was created a few years ago before Yarn and offline mirror feature: https://yarnpkg.com/blog/2016/11/24/offline-mirror/.

There is even a feature to store built artifacts https://github.com/yarnpkg/yarn/pull/5314 (I should have written a blog post about it but was too busy with other projects).

So unless you really want to send a PR to support Yarn in npm-git-lock I suggest you to switch to offline mirror in Yarn
